# Generated by Django 6.0.4 on 2026-04-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('analyst', 'Analyst'), ('support', 'Support'), ('end_user', 'End User')], default='end_user', max_length=20),
        ),
    ]
