# Generated by Django 6.0.4 on 2026-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
