# Generated by Django 6.0.4 on 2026-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_blocked_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('analyst', 'Analyst'), ('support', 'Support'), ('end_user', 'End User'), ('admin', 'Admin')], default='end_user', max_length=20),
        ),
    ]
