# Generated by Django 6.0.4 on 2026-04-26 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_account_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudFlag',
        ),
    ]
