# Generated by Django 6.0.4 on 2026-04-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_delete_fraudflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100.0, editable=False, max_digits=12),
        ),
    ]
