# Generated by Django 6.0.4 on 2026-05-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='destination_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
