# Generated by Django 6.0.4 on 2026-05-03 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0008_alter_fraudflag_transaction'),
        ('transactions', '0008_remove_transaction_account_debittransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
