# Generated by Django 6.0.4 on 2026-05-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_debittransaction_account_creditrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditrequest',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request', to='transactions.credittransaction'),
        ),
    ]
