# Generated by Django 6.0.4 on 2026-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_creditrequest_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrequest',
            name='transaction',
        ),
        migrations.AddField(
            model_name='creditrequest',
            name='fraud',
            field=models.BooleanField(default=False),
        ),
    ]
