# Generated by Django 6.0.4 on 2026-05-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_remove_creditrequest_transaction_creditrequest_fraud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fraud_blocked', 'Fraud Blocked'), ('at_support', 'At Support')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('fraud_blocked', 'Fraud Blocked'), ('at_support', 'At Support')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='debittransaction',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('fraud_blocked', 'Fraud Blocked'), ('at_support', 'At Support')], default='completed', max_length=20),
        ),
    ]
