# Generated by Django 6.0.4 on 2026-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_reversaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debittransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manualdebittransaction',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
    ]
