# Generated by Django 6.0.4 on 2026-04-26 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0001_initial'),
        ('transactions', '0003_delete_fraudflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudflag',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag', to='transactions.transaction'),
        ),
    ]
