# Generated by Django 6.0.4 on 2026-04-30 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0003_alter_fraudflag_transaction_fraudeventlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FraudEventLog',
        ),
    ]
