# Generated by Django 6.0.4 on 2026-05-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0004_delete_fraudeventlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudflag',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20),
        ),
    ]
