# Generated by Django 6.0.4 on 2026-05-01 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0006_alter_fraudflag_transaction'),
        ('transactions', '0004_alter_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudflag',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag', to='transactions.transaction'),
        ),
    ]
