# Generated by Django 6.0.4 on 2026-05-03 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0007_alter_fraudflag_transaction'),
        ('transactions', '0008_remove_transaction_account_debittransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraudflag',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag', to='transactions.debittransaction'),
        ),
    ]
