# Generated by Django 6.0.4 on 2026-05-03 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0008_alter_fraudflag_transaction'),
        ('transactions', '0012_remove_creditrequest_transaction_creditrequest_fraud'),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudflag',
            name='credit_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.creditrequest'),
        ),
        migrations.AlterField(
            model_name='fraudflag',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_flag', to='transactions.debittransaction'),
        ),
    ]
