# Generated by Django 6.0.4 on 2026-05-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudlog', '0009_fraudflag_credit_request_alter_fraudflag_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fraudflag',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fraudflag',
            name='resolved_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
